trigger:
- main

variables:
  TF_VERSION: '1.3.7'
  WORKING_DIR: '$(System.DefaultWorkingDirectory)'
  AZURE_SUBSCRIPTION: 'SC-Terraform-Azure'   # Nome da sua Service Connection
  RESOURCE_GROUP: 'RG02'                     # <- Ajustar aqui
  STORAGE_ACCOUNT: 'restorevmrg02'           # <- Ajustar aqui
  CONTAINER_NAME: 'tfstate'

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Instala o Terraform
- bash: |
    echo "Instalando Terraform $(TF_VERSION)..."
    wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
    unzip terraform_$(TF_VERSION)_linux_amd64.zip
    sudo install terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

# 2. Login no Azure
- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: '$(AZURE_SUBSCRIPTION)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Verificando se o container $(CONTAINER_NAME) existe..."

      # Checa se o container já existe
      EXISTING_CONTAINER=$(az storage container exists \
        --name $(CONTAINER_NAME) \
        --account-name $(STORAGE_ACCOUNT) \
        --auth-mode login \
        --query exists)

      echo "Container existente: $EXISTING_CONTAINER"

      if [ "$EXISTING_CONTAINER" == "false" ]; then
        echo "Container não existe. Criando..."
        az storage container create \
          --name $(CONTAINER_NAME) \
          --account-name $(STORAGE_ACCOUNT) \
          --auth-mode login
      else
        echo "Container já existe. Nada a fazer."
      fi

# 3. Rodar o Terraform
- bash: |
    cd $(WORKING_DIR)

    echo "Inicializando Terraform..."
    terraform init \
      -backend-config="resource_group_name=$(RESOURCE_GROUP)" \
      -backend-config="storage_account_name=$(STORAGE_ACCOUNT)" \
      -backend-config="container_name=$(CONTAINER_NAME)" \
      -backend-config="key=prod.tfstate"

    echo "Executando Terraform Plan..."
    terraform plan -out=tfplan -var-file=prod.tfvars

    echo "Aplicando mudanças..."
    terraform apply -auto-approve tfplan
  displayName: 'Run Terraform'
