trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  backendResourceGroup: 'RG02'
  backendStorageAccount: 'restorevmrg02'
  backendContainerName: 'tfstate'
  backendKey: 'prod.tfstate'

steps:

# 1. Login no Azure usando o Service Connection (Service Principal)
- task: AzureCLI@2
  displayName: 'Login no Azure'
  inputs:
    azureSubscription: 'SC-Terraform-Azure'   # Nome do Service Connection configurado no Azure DevOps
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Login realizado com sucesso."

# 2. Inicializa o Terraform apontando para o backend
- task: Bash@3
  displayName: 'Terraform Init'
  inputs:
    targetType: 'inline'
    script: |
      terraform init \
        -backend-config="resource_group_name=$(backendResourceGroup)" \
        -backend-config="storage_account_name=$(backendStorageAccount)" \
        -backend-config="container_name=$(backendContainerName)" \
        -backend-config="key=$(backendKey)"

# 3. Executa o Terraform Plan
- task: Bash@3
  displayName: 'Terraform Plan'
  inputs:
    targetType: 'inline'
    script: |
      terraform plan -out=tfplan

# 4. Executa o Terraform Apply (aplica mudanças)
- task: Bash@3
  displayName: 'Terraform Apply'
  inputs:
    targetType: 'inline'
    script: |
      terraform apply tfplan
